### ISSUE TITLE
Refactor indexes section in the config

### ISSUE THREAD

**Issue by dmitryduev** [dmitryduev/kowalski#13]
Should be:

```yaml
database:
  indexes:
    <catalog>:
      - name: <name>
        fields: <list of field names and directions>
        unique: <true|false>
```
