### ISSUE TITLE
Primary/secondary instances of Kowalski for querying

### ISSUE THREAD

**Issue by dmitryduev** [dmitryduev/kowalski#60]
This should be discussed with the team to see what the implementation should look like.

**Feature Summary**
Implement a mode that would allow multiple instances of Kowalski to operate under one "umbrella". 

**Usage / behavior**
The user would query a primary instance of K. If the latter does not find the requested catalog in its db, it would ask secondary instances to see if they have it, and query them if they do.

**Alternative Solutions**
- MongoDB sharding.
- Sync the users across instances, report the "routing" info to the user; decide under the hood on the `penquins` side what instance to query

**Implementation details**
In config.yaml, set up 
```yaml
{
  primary_instance: <false|true>
  secondary_instances: <list of known secondary instances access info>
}
```
